; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env]
platform 					= wizio-pico
board 						= raspberry-pi-pico
framework 					= baremetal
board_build.sdk				= SDK151
board_build.optimization 	= -O2 ;-Og ;-Os ;-O2
board_build.heap 			= 1024 ;2048
board_build.stack			= 1024 ;2048
;board_build.pio 			= lib/sdcard/spi.pio
board_build.boot 			= mulx4 ;generic_03h;is25lp080;usb_blinky;w25q080;w25x10cl
board_build.release_dir		= ../../../release/
board_build.app_version		= 096_17

monitor_port = COM3
;monitor_port = COM100
monitor_speed = 921600
upload_protocol = picotool
debug_tool = picoprobe
;debug_build_flags = -O0 -ggdb3 -g3

lib_deps = 	joy
			sdcard
			fatfs
;build_flags = -D Z80_DEBUG
;build_flags =	-D DEBUG_DISABLE_LOADERS


monitor_filters =
  send_on_enter
  printable
  time      ; Add timestamp with milliseconds for each new line

[env:murmulator-vga-hdmi-tft]
board_build.app_name 		= murm_vga-hdmi-tft 
build_flags =	-D VGA_HDMI
				-D PICO_STDIO_USB
				-Wl,-Map,output.map
build_unflags = -D PICO_STDIO_UART
lib_deps =		video
				joy
lib_ignore =	tv_out
				tv_out_soft
				tft

[env:murmulator-composite]
board_build.app_name 		= murm_composite
build_flags = 
	-D COMPOSITE_TV
	-D PICO_STDIO_USB
	
build_unflags = 
	-D PICO_STDIO_UART
lib_deps =		tv_out
				joy
lib_ignore =	video
				tv_out_soft
				tft

[env:murmulator-soft-composite]
board_build.app_name 		= murm_soft_composite
build_flags = 
	-D SOFT_COMPOSITE_TV
	-D PICO_STDIO_USB
	-D SOFT_CVBS_NO_HUD
build_unflags = 
	-D PICO_STDIO_UART
lib_deps =		tv_out_soft
				joy
lib_ignore =	video
				tv_out
				tft

